//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionPrestamos.java
//  @ Date : 8/19/2026
//  @ Author : 
//
//
import java.util.List;
import java.util.ArrayList;



public class GestionPrestamos {
	private List<Prestamo> listaPrestamos;

	public GestionPrestamos(){
		this.listaPrestamos = new ArrayList<>();
	}

	public void agregarPrestamo(Prestamo prestamo) {
		this.listaPrestamos.add(prestamo);
	}
	
	public Prestamo buscarPorCodigo(float codigo) {
    for (Prestamo prestamo : this.listaPrestamos) {
        if (prestamo.getCodigo() == codigo) {
            return prestamo; // Return the exact object when matched
        }
    }
    return null; // Return null if no matching loan code exists
}
	
	public boolean modificarPrestamo(float codigo, Prestamo nuevoPrestamo) {
		for(int i=0; i<this.listaPrestamos.size(); i++){
			if(this.listaPrestamos.get(i).getCodigo() == codigo){
				this.listaPrestamos.set(i, nuevoPrestamo);
				return true;
			}
		}
		return false;
	}
	
	public void buscarPorEstudiante(int carnet) {
		boolean encontrado = false;
		System.out.println("\n--- Préstamos para el carnet: " + carnet + " ---");
		for (Prestamo prestamo : this.listaPrestamos) {
			if (prestamo.getCarnet() == carnet) {
				System.out.println(prestamo);
				encontrado = true;
			}
		}

		if (!encontrado) {
			System.out.println("No se encontraron préstamos registrados con el carnet " + carnet);
		}
	}
	
	public int calcularTotalDias() {
		int totalDias = 0;
		for(Prestamo prestamo : this.listaPrestamos){
			totalDias += prestamo.getDiasAutorizados();
		}
		return totalDias;
		}
	
	
	public Prestamo obtenerPrestamoConMayorDias() {
		Prestamo mayorPrestamo = this.listaPrestamos.get(0);
		for(Prestamo prestamo : this.listaPrestamos){
			if(prestamo.getDiasAutorizados()> mayorPrestamo.getDiasAutorizados()){
				mayorPrestamo = prestamo;
			}
		}
		return mayorPrestamo;
	}
	
	
	public void obtenerTodosLosPrestamos() {
		System.out.println("-----Todos los Prestamos-----");
		for(Prestamo prestamo : this.listaPrestamos){
			System.out.println(prestamo);
		}
	}

	public boolean devolerPrestamo(float codigo){
		for(int i= 0; i<this.listaPrestamos.size(); i++){
			if(this.listaPrestamos.get(i).getCodigo() == codigo){
				this.listaPrestamos.remove(i);
				return true;
			}
		}
		return false;

	}
}
