//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 8/19/2026
//  @ Author : 
//
//


import java.util.Scanner;
import java.util.InputMismatchException;

public class Main {
	public static void main(String[] args) {
		GestionPrestamos gestion = new GestionPrestamos();
		Scanner scanner = new Scanner(System.in);
		int opcion = 0;

		do{
			System.out.println("·····Menu de Prestamos·····");
			System.out.println("1. Agregar prestamo");
			System.out.println("2. Modificar prestamo");
			System.out.println("3. Devolver Prestamo");
			System.out.println("4. Mostrar todos los prestamos");
			System.out.println("5. Mostrar prestamo con mas dias");
			System.out.println("6. Buscar prestamos por carnet");
			System.out.println("7. Buscar por codigo");
			System.out.println("8. Salir");
			
			try {
				System.out.print("ELIJA UNA OPCION: ");
				opcion = scanner.nextInt();
			} catch (InputMismatchException e) {
				System.out.println("¡ERROR! Debe ingresar un número válido.");
				scanner.nextLine(); 
				continue; 
			}

			switch(opcion){
				case 1:
					
						float codigo = leerFloatValido(scanner, "Ingrese su codigo (Ej: 23.5): ");
						
						int carnet = leerEnteroValido(scanner, "Ingrese su carnet: ");

						System.out.println("Ingrese su nombre: ");
						String nombre = scanner.nextLine();
						
						System.out.println("Ingrese el titulo del libro: ");
						String tituloLibro = scanner.nextLine();

						System.out.println("Ingrese los dias autorizados: ");
						int diasAutorizados = scanner.nextInt();
						
						Prestamo pres = new Prestamo(codigo, carnet, nombre, tituloLibro, diasAutorizados);
						gestion.agregarPrestamo(pres);
					

					break;

				case 2:

					float codigoMod = leerFloatValido(scanner, "Ingrese codigo del prestamo a modificar: ");
						
					int nuevoCarnet = leerEnteroValido(scanner, "Nuevo carnet: ");
					

					System.out.print("Nuevo nombre: ");
					String nuevoNombre = scanner.nextLine();

					System.out.print("Nuevo título del libro: ");
					String nuevoTitulo = scanner.nextLine();

					System.out.print("Nuevos días autorizados: ");
					int nuevosDias = scanner.nextInt();

					Prestamo prestamoModificado = new Prestamo(codigoMod, nuevoCarnet, nuevoNombre, nuevoTitulo, nuevosDias);

					boolean modificado = gestion.modificarPrestamo(codigoMod, prestamoModificado);

					if (modificado) {
						System.out.println("¡Préstamo modificado exitosamente!");
					} else {
						System.out.println("No se encontró un préstamo con ese código.");
					}
					break;
				
				case 3:
					
					float codigoDevolver = leerFloatValido(scanner, "Ingrese el codigo del prestamo que quiere devolver: ");

					boolean devuelto = gestion.devolerPrestamo(codigoDevolver);

					if (devuelto) {
						System.out.println("¡Préstamo devuelto exitosamente!");
					} else {
						System.out.println("No se encontró ningún préstamo con ese código.");
					}
					break;

				case 4:
					gestion.obtenerTodosLosPrestamos();
    				break;

				case 5:
					Prestamo mayor = gestion.obtenerPrestamoConMayorDias();

					if (mayor != null) {
						System.out.println("Préstamo con más días: " + mayor);
					} else {
						System.out.println("No hay préstamos registrados.");
					}
					break;
				
				case 6:
					int carnetBuscar = leerEnteroValido(scanner, "Ingrese el carnet del estudiante: ");

					gestion.buscarPorEstudiante(carnetBuscar);
					break;

				case 7:
					float codigoBuscar = leerFloatValido(scanner, "Ingrese el codigo: ");
					Prestamo encontrado = gestion.buscarPorCodigo(codigoBuscar);
					if (encontrado != null) {
                        System.out.println("Préstamo encontrado: " + encontrado);
                    } else {
                        System.out.println("No existe ningún préstamo registrado con el código " + codigoBuscar);
                    }
                    break;

				case 8:
					System.out.println("Saliendo del programa...");
					break;
			}

		} while(opcion !=8 );
		scanner.close();
	}
	private static int leerEnteroValido(Scanner scanner, String mensaje) {
        while (true) {
            try {
                System.out.print(mensaje);
                int valor = scanner.nextInt();
                scanner.nextLine();
                return valor;
            } catch (InputMismatchException e) {
                System.out.println("Error: Debe ingresar un número entero válido.");
                scanner.nextLine();
            }
        }
    }

    private static float leerFloatValido(Scanner scanner, String mensaje) {
        while (true) {
            try {
                System.out.print(mensaje);
                float valor = scanner.nextFloat();
                scanner.nextLine();
                return valor;
            } catch (InputMismatchException e) {
                System.out.println("Error: Debe ingresar un número válido.");
                scanner.nextLine();
            }
        }
    }
}
	
