//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Prestamo.java
//  @ Date : 8/19/2026
//  @ Author : 
//
//




public class Prestamo {
	private float codigo;
	private int carnet;
	private String nombre;
	private String tituloLibro;
	private int diasAutorizados;

	Prestamo(float codigo, int carnet, String nombre, String tituloLibro, int  diasAutorizados){
		this.codigo = codigo;
        this.carnet = carnet;
        this.nombre = nombre;
		this.tituloLibro = tituloLibro;
		this.diasAutorizados = diasAutorizados;
	}


	public float getCodigo() {
		return codigo;
	}
	
	public int getCarnet() {
		return carnet;
	}
	
	public String getNombre() {
		return nombre;
	}
	
	public String getTituloLibro() {
		return tituloLibro;
	}
	
	public int getDiasAutorizados() {
		return diasAutorizados;
	}

	public String toString() {
    return "Prestamo [Código: " + codigo + ", Nombre: " + nombre + ", Carnet: " + carnet + ", Titulo: " + tituloLibro + ", Días: " + diasAutorizados + "]";
	}
}
