//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ArmamentoEspecial.java
//  @ Date : 8/7/2026
//  @ Author : 
//
//



public class ArmamentoEspecial {
	private String nombre;
	private TipoEfecto tipoEfecto;
	private double probabilidad;
	private int valor;

	public ArmamentoEspecial(String nombre, TipoEfecto tipoEfecto, double probabilidad, int valor){
		this.nombre = nombre;
		this.tipoEfecto = tipoEfecto;
		this.probabilidad = probabilidad;
		this.valor = valor;
	}
	
	public boolean activar(){
		double aleatorio = Math.random();
		if (aleatorio <= this.probabilidad){
			return true;
		}
		else{
			return false;
		}

	}


	public void aplicar() {

	}

	public TipoEfecto getTipoEfecto() {
    return this.tipoEfecto;
	}

	public int getValor() {
		return this.valor;
	}

	
}
