//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Champion.java
//  @ Date : 8/7/2026
//  @ Author : 
//
//




public class Champion {
	private String nombre;
	private TipoPal tipo;
	private int ataque;
	private int defensa;
	private ArmamentoEspecial armamentoEspecial;
	private int bonusAtaque;
	private int bonusDefensa;
	private boolean usado;
	private int rondasEfecto;


	public Champion(String nombre, TipoPal tipo, int ataque, int defensa, ArmamentoEspecial armamentoEspecial){
		this.nombre = nombre;
		this.tipo = tipo;
		this.ataque = ataque;
		this.defensa = defensa;
		this.armamentoEspecial = armamentoEspecial;
		this.bonusAtaque = 0;
		this.bonusDefensa = 0;
		this.usado = false;
		this.rondasEfecto = 0;
	}

	public String getNombre() {
    return this.nombre;
}

	public TipoPal getTipo() {
		return this.tipo;
	}

	public int getAtaque() {
		return this.ataque;
	}

	public int getDefensa() {
		return this.defensa;
	}


	public ArmamentoEspecial getArmamentoEspecial() {
		return this.armamentoEspecial;
	}

	public int calcularAtaque() {
		return this.ataque + this.bonusAtaque;
	}
	
	public void usarArmamento() {
		if (this.armamentoEspecial.activar()) {
        System.out.println("¡El armamento especial se ha activado con éxito!");
        
        this.rondasEfecto = 2;
        
        aplicarBonus();
    } else {
        System.out.println("El armamento especial falló al intentar activarse.");
    }
	}
	
	public void aplicarBonus() {
		if (this.armamentoEspecial.getTipoEfecto() == TipoEfecto.AumentarAtaque) {
        this.bonusAtaque = this.armamentoEspecial.getValor();
    } else if (this.armamentoEspecial.getTipoEfecto() == TipoEfecto.AumentarDefensa) {
        this.bonusDefensa = this.armamentoEspecial.getValor();
    }
	}
	
	public void disminuirBonus() {
		if (this.rondasEfecto > 0) {
        this.rondasEfecto--; 
        
        
        if (this.rondasEfecto == 0) {
            this.bonusAtaque = 0;
            this.bonusDefensa = 0;
        }
    }
	}
	
	public boolean estaDisponible() {
		return !this.usado;
	}
	
	public void markUsado() {
		this.usado = true;
	}
}
