//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entrenador.java
//  @ Date : 8/7/2026
//  @ Author : 
//
//




public class Entrenador {
	private String nombre;
	private Champion[] equipo;
	private int rondasGanadas;

	public Entrenador(String nombre){
		this.nombre = nombre;
		this.equipo = new Champion[3];
		this.rondasGanadas = 0;
	}


	public void agregarPal(Champion pal, int posicion) {
		if(posicion >= 0 && posicion < 3){
			this.equipo[posicion] = pal;
		}
	}
	
	public Champion seleccionarPal(int posicion) {
		if (posicion >= 0 && posicion < 3) {
            return this.equipo[posicion];
        }
        return null;
	}
	
	public void sumaVictorias() {
		this.rondasGanadas++;
	}
	
	public String getNombre() {
		return this.nombre;
	}
	
	public Champion[] getEquipo() {
		return this.equipo;
	}
	
	public int getRondasGanadas() {
		return this.rondasGanadas;
	}
}
