import java.util.Random;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 8/7/2026
//  @ Author : 
//
//




public class Main {
	public static void main(String[] args) {
		// 1. Creamos algunos Armamentos Especiales
        // Parametros: nombre, probabilidadExito (0.0 a 1.0), tipoEfecto, valor
        ArmamentoEspecial espada = new ArmamentoEspecial("Espada Ignea", TipoEfecto.AumentarAtaque, 0.3, 15);
		ArmamentoEspecial escudo = new ArmamentoEspecial("Escudo de Roble", TipoEfecto.AumentarDefensa, 0.4, 10);
		ArmamentoEspecial tridente = new ArmamentoEspecial("Tridente de las Mareas", TipoEfecto.AumentarAtaque, 0.2, 20);

        // 2. Creamos los Champions para el Entrenador 1
        Champion champ1 = new Champion("Flarion", TipoPal.Fuego, 50, 30, espada);
        Champion champ2 = new Champion("Verdant", TipoPal.Planta, 45, 40, escudo);
        Champion champ3 = new Champion("Aqualis", TipoPal.Agua, 40, 35, tridente);

        // 3. Creamos los Champions para el Entrenador 2
        Champion champ4 = new Champion("Ember", TipoPal.Fuego, 50, 35, espada);
        Champion champ5 = new Champion("Sylvan", TipoPal.Planta, 45, 40, escudo);
        Champion champ6 = new Champion("Nautilus", TipoPal.Agua, 40, 30, tridente);

        // 4. Crear los Entrenadores y asignarles su equipo de 3 criaturas
        Entrenador e1 = new Entrenador("Ash");
        e1.agregarPal(champ1, 0);
        e1.agregarPal(champ2, 1);
        e1.agregarPal(champ3, 2);

        Entrenador e2 = new Entrenador("Gary");
        e2.agregarPal(champ4, 0);
        e2.agregarPal(champ5, 1);
        e2.agregarPal(champ6, 2);

        // 5. Iniciar la partida
        Partida partida = new Partida(e1, e2);
        partida.iniciarPartida();
	}
}
