//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Partida.java
//  @ Date : 8/7/2026
//  @ Author : 
//
//




public class Partida {
	private Entrenador entrenador1;
	private Entrenador entrenador2;
	private int rondaActual;

	public Partida(Entrenador entrenador1, Entrenador entrenador2){
		this.entrenador1 = entrenador1;
		this.entrenador2 = entrenador2;
		this.rondaActual = 1;

	}


	public void iniciarPartida() {
		java.util.Scanner scanner = new java.util.Scanner(System.in);

		System.out.println("=================================");
		System.out.println("¡INICIA LA BATALLA DE CHAMPIONS!");
		System.out.println("=================================");

		// El juego consta de 3 rondas
		for (int i = 0; i < 3; i++) {
			System.out.println("\n--- Selección de Criatura ---");
			System.out.print(this.entrenador1.getNombre() + ", elige el índice de tu criatura (0, 1 o 2): ");
			int p1 = scanner.nextInt();

			System.out.print(this.entrenador2.getNombre() + ", elige el índice de tu criatura (0, 1 o 2): ");
			int p2 = scanner.nextInt();

			jugarRonda(p1, p2);
		}

		// Anuncio del ganador
		Entrenador ganador = ganadorFinal();
		System.out.println("\n=================================");
		if (ganador != null) {
			System.out.println("¡EL GANADOR FINAL ES: " + ganador.getNombre().toUpperCase() + "!");
		} else {
			System.out.println("¡LA PARTIDA HA TERMINADO EN EMPATE!");
		}
		System.out.println("=================================");
	}
	
	public void jugarRonda(int poke1, int poke2) {
		Champion pal1 = this.entrenador1.seleccionarPal(poke1);
		Champion pal2 = this.entrenador2.seleccionarPal(poke2);

		// 1. Validar que ambas criaturas existan y estén disponibles
		if (pal1 == null || pal2 == null) {
			System.out.println("Selección inválida. Intenta de nuevo.");
			return;
		}

		if (!pal1.estaDisponible() || !pal2.estaDisponible()) {
			System.out.println("Una de las criaturas elegidas ya fue usada en una ronda anterior.");
			return;
		}

		System.out.println("\n--- RONDA " + this.rondaActual + " ---");
		System.out.println(this.entrenador1.getNombre() + " elige a " + pal1.getNombre());
		System.out.println(this.entrenador2.getNombre() + " elige a " + pal2.getNombre());

		// 2. Intentar activar armamento especial
		pal1.usarArmamento();
		pal2.usarArmamento();

		// 3. Calcular bono por ventaja de tipo
		int ventaja1 = calcularEfectoTipo(pal1, pal2);
		int ventaja2 = calcularEfectoTipo(pal2, pal1);

		// 4. Calcular poder total de cada una (ataque base + bonus arma + ventaja tipo)
		int poderTotal1 = pal1.calcularAtaque() + ventaja1;
		int poderTotal2 = pal2.calcularAtaque() + ventaja2;

		// 5. Determinar ganador de la ronda y marcar como usadas
		determinarGanadorRonda(pal1, pal2, poderTotal1, poderTotal2);

		// 6. Reducir la duración de los bonos temporales y avanzar la ronda
		pal1.disminuirBonus();
		pal2.disminuirBonus();
		this.rondaActual++;
}
	
	public void calcularVentajaTipo() {
	}
	
	public void determinarGanadorRonda(Champion pal1, Champion pal2, int poder1, int poder2) {
		System.out.println("Poder total de " + pal1.getNombre() + ": " + poder1);
		System.out.println("Poder total de " + pal2.getNombre() + ": " + poder2);

		if (poder1 > poder2) {
			System.out.println("¡" + this.entrenador1.getNombre() + " gana la ronda!");
			this.entrenador1.sumaVictorias();
		} else if (poder2 > poder1) {
			System.out.println("¡" + this.entrenador2.getNombre() + " gana la ronda!");
			this.entrenador2.sumaVictorias();
		} else {
			System.out.println("¡Es un empate en esta ronda! Ninguno suma puntos.");
		}

		
		pal1.markUsado();
		pal2.markUsado();
	}
	
	public int calcularEfectoTipo(Champion atacante, Champion defensor) {
		TipoPal tipoA = atacante.getTipo();
		TipoPal tipoD = defensor.getTipo();

		// Verificamos si el atacante tiene ventaja sobre el defensor
		if (tipoA == TipoPal.Fuego && tipoD == TipoPal.Planta) {
			return 20; // Ventaja
		} else if (tipoA == TipoPal.Planta && tipoD == TipoPal.Agua) {
			return 20; // Ventaja
		} else if (tipoA == TipoPal.Agua && tipoD == TipoPal.Fuego) {
			return 20; // Ventaja
		}

		return 0; // Sin ventaja
	}
	
	public Entrenador ganadorFinal() {
		if (this.entrenador1.getRondasGanadas() > this.entrenador2.getRondasGanadas()) {
        return this.entrenador1;
    } else if (this.entrenador2.getRondasGanadas() > this.entrenador1.getRondasGanadas()) {
        return this.entrenador2;
    } else {
        return null; // Empate general
    }
	}
}
