//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorSimulador.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




public class ControladorSimulador {
    private SimuladorMision simulador;
    private VistaConsola vista;

    public ControladorSimulador(SimuladorMision simulador, VistaConsola vista) {
        this.simulador = simulador;
        this.vista = vista;
    }

    // Bucle principal de navegación controlado por la opción seleccionada por el usuario
    public void iniciar() {
        boolean salir = false;
        while (!salir) {
            int opcion = vista.mostrarMenuPrincipal();
            
            // Estructura switch para redirigir el flujo según la opción del menú
            switch (opcion) {
                case 1:
                    crearModulo();
                    break;
                case 2:
                    String resultadoCiclo = simulador.ejecutarCiclo();
                    vista.mostrarMensaje(resultadoCiclo);
                    break;
                case 3:
                    mostrarEstado();
                    break;
                case 4:
                    recargarModuloVuelo();
                    break;
                case 5:
                    salir = true;
                    vista.mostrarMensaje("Saliendo de la simulación...");
                    break;
                default:
                    vista.mostrarMensaje("Opción no válida.");
            }
        }
    }

    public void crearModulo() {
        int tipo = vista.pedirTipoModulo();
        String id = vista.pedirString("ID del módulo: ");
        String nombre = vista.pedirString("Nombre del módulo: ");
        double salud = vista.pedirDouble("Salud inicial (0 - 100): ");
        double costo = vista.pedirDouble("Costo de construcción: ");

        // Switch para instanciar la subclase específica que eligió el usuario
        switch (tipo) {
            case 1:
                double empuje = vista.pedirDouble("Empuje: ");
                double consumoVuelo = vista.pedirDouble("Consumo de combustible por ciclo: ");
                double capacidadT = vista.pedirDouble("Capacidad del tanque: ");
                double nivelComb = vista.pedirDouble("Nivel de combustible actual: ");
                
                // Instanciamos ModuloVuelo y lo pasamos al simulador (Upcasting)
                ModuloVuelo mv = new ModuloVuelo(id, nombre, salud, true, costo, empuje, consumoVuelo, nivelComb, capacidadT);
                simulador.agregarModulo(mv);
                vista.mostrarMensaje("Módulo de Vuelo creado exitosamente.");
                break;

            case 2:
                double vel = vista.pedirDouble("Velocidad de manejo: ");
                double consumoEnergia = vista.pedirDouble("Consumo de energía por ciclo: ");
                double capacidadCarga = vista.pedirDouble("Capacidad de carga: ");
                
                ModuloTierra mt = new ModuloTierra(id, nombre, salud, true, costo, vel, consumoEnergia, capacidadCarga);
                simulador.agregarModulo(mt);
                vista.mostrarMensaje("Módulo Terrestre creado exitosamente.");
                break;

            case 3:
                double genEnergia = vista.pedirDouble("Generación de energía por ciclo: ");
                double capBateria = vista.pedirDouble("Capacidad de la batería: ");
                double nivelBat = vista.pedirDouble("Nivel de energía actual: ");
                
                ModuloEnergia me = new ModuloEnergia(id, nombre, salud, true, costo, genEnergia, capBateria, nivelBat);
                simulador.agregarModulo(me);
                vista.mostrarMensaje("Módulo de Energía creado exitosamente.");
                break;

            default:
                vista.mostrarMensaje("Tipo de módulo no reconocido.");
        }
    }

    public void mostrarEstado() {
        vista.mostrarMensaje(simulador.getEstado().toString());
        vista.mostrarMensaje("--- MÓDULOS REGISTRADOS ---");
        if (simulador.getModulos().isEmpty()) {
            vista.mostrarMensaje("No hay módulos registrados.");
        } else {
            // Forzamos el casteo explícito del objeto a Modulo para corregir la incompatibilidad
            for (Object obj : simulador.getModulos()) {
                Modulo m = (Modulo) obj;
                vista.mostrarMensaje(m.toString());
            }
        }
    }

    public void recargarModuloVuelo() {
        String id = vista.pedirString("Ingrese el ID del Módulo de Vuelo a recargar: ");
        Modulo seleccionado = null;

        // Bucle de búsqueda haciendo el casteo seguro elemento por elemento
        for (Object obj : simulador.getModulos()) {
            Modulo m = (Modulo) obj;
            if (m.getId().equalsIgnoreCase(id)) {
                seleccionado = m;
                break;
            }
        }

        // Operador 'instanceof' + Downcasting: validamos si el objeto encontrado es de tipo ModuloVuelo
        if (seleccionado instanceof ModuloVuelo) {
            double cantidad = vista.pedirDouble("Cantidad de combustible a recargar: ");
            ((ModuloVuelo) seleccionado).recargarCombustible(cantidad);
            vista.mostrarMensaje("Combustible recargado. Nuevo nivel: " + ((ModuloVuelo) seleccionado).getNivelCombustibleActual());
        } else if (seleccionado != null) {
            vista.mostrarMensaje("El módulo con ID " + id + " no es un Módulo de Vuelo.");
        } else {
            vista.mostrarMensaje("No se encontró ningún módulo con el ID especificado.");
        }
    }
}
