//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EstadoMision.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




public class EstadoMision {
    private double distanciaRestanteAlObjetivo;
    private double reservaEnergia;
    private double reservaCombustible;
    private double mineralRecolectado;

    public EstadoMision() {}

    public EstadoMision(double distanciaRestanteAlObjetivo, double reservaEnergia, double reservaCombustible, double mineralRecolectado) {
        this.distanciaRestanteAlObjetivo = distanciaRestanteAlObjetivo;
        this.reservaEnergia = reservaEnergia;
        this.reservaCombustible = reservaCombustible;
        this.mineralRecolectado = mineralRecolectado;
    }

    // Getters y Setters para manipular las variables globales de la simulación
    public double getDistanciaRestanteAlObjetivo() { return distanciaRestanteAlObjetivo; }
    public void setDistanciaRestanteAlObjetivo(double distanciaRestanteAlObjetivo) { this.distanciaRestanteAlObjetivo = distanciaRestanteAlObjetivo; }

    public double getReservaEnergia() { return reservaEnergia; }
    public void setReservaEnergia(double reservaEnergia) { this.reservaEnergia = reservaEnergia; }

    public double getReservaCombustible() { return reservaCombustible; }
    public void setReservaCombustible(double reservaCombustible) { this.reservaCombustible = reservaCombustible; }

    public double getMineralRecolectado() { return mineralRecolectado; }
    public void setMineralRecolectado(double mineralRecolectado) { this.mineralRecolectado = mineralRecolectado; }

    @Override
    public String toString() {
        return "=== ESTADO DE LA MISIÓN ===" +
               "\nDistancia restante: " + distanciaRestanteAlObjetivo + " km" +
               "\nReserva de Energía: " + reservaEnergia + " unidades" +
               "\nReserva de Combustible: " + reservaCombustible + " L" +
               "\nMineral Recolectado: " + mineralRecolectado + " kg\n";
    }
}