//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




public class Main {
    public static void main(String[] args) {
        // Inicialización de la configuración básica de la misión espacial
        EstadoMision estadoInicial = new EstadoMision(1000.0, 500.0, 300.0, 0.0);
        
        // Instanciación de componentes principales del patrón MVC
        SimuladorMision simulador = new SimuladorMision(estadoInicial);
        VistaConsola vista = new VistaConsola();

        // Inyección de dependencias al controlador para conectar la vista con la simulación
        ControladorSimulador controlador = new ControladorSimulador(simulador, vista);
        controlador.iniciar();
    }
}
