//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModuloEnergia.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




public class ModuloEnergia extends Modulo {
    private double generacionEnergiaPorCiclo;
    private double capacidadBateria;
    private double nivelEnergiaActual;

    public ModuloEnergia() {}

    public ModuloEnergia(String id, String nombre, double salud, boolean activo, double costoDeConstruccion,
                         double generacionEnergiaPorCiclo, double capacidadBateria, double nivelEnergiaActual) {
        super(id, nombre, salud, activo, costoDeConstruccion);
        this.generacionEnergiaPorCiclo = generacionEnergiaPorCiclo;
        this.capacidadBateria = capacidadBateria;
        this.nivelEnergiaActual = nivelEnergiaActual;
    }

    public double getGeneracionEnergiaPorCiclo() { return generacionEnergiaPorCiclo; }
    public double getCapacidadBateria() { return capacidadBateria; }
    public double getNivelEnergiaActual() { return nivelEnergiaActual; }
    public void setNivelEnergiaActual(double nivelEnergiaActual) { this.nivelEnergiaActual = nivelEnergiaActual; }

    @Override
    public String procesarCiclo(EstadoMision estado) {
        if (!activo) {
            return "El módulo de energía [" + nombre + "] está inactivo.";
        }

        // Este módulo incrementa los recursos del sistema en lugar de consumirlos
        double generada = generacionEnergiaPorCiclo;
        this.nivelEnergiaActual = Math.min(capacidadBateria, nivelEnergiaActual + generada);
        
        // Aumentamos la reserva global de la misión para que otros módulos (como el de tierra) puedan usarla
        estado.setReservaEnergia(estado.getReservaEnergia() + generada);

        return "Módulo de Energía [" + nombre + "] generó " + generada + 
               " unidades de energía (Batería interna: " + nivelEnergiaActual + "/" + capacidadBateria + ").";
    }
}
