//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Modulo.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




// Clase abstracta: sirve como la plantilla base para todos los tipos de módulos.
// No se pueden crear objetos directamente de esta clase con 'new Modulo()'.
public abstract class Modulo {
    // Usamos 'protected' para que las subclases (Vuelo, Tierra, Energia) puedan usar
    // estos atributos directamente sin necesidad de llamar a los getters dentro de ellas.
    protected String id;
    protected String nombre;
    protected double salud;
    protected boolean activo;
    protected double costoDeConstruccion;

    public Modulo() {}

    public Modulo(String id, String nombre, double salud, boolean activo, double costoDeConstruccion) {
        this.id = id;
        this.nombre = nombre;
        this.salud = salud;
        this.activo = activo;
        this.costoDeConstruccion = costoDeConstruccion;
    }

    public String getId() { return id; }
    public String getNombre() { return nombre; }
    public boolean estaActivo() { return activo; }
    public void setActivo(boolean activo) { this.activo = activo; }
    public double getCostoDeConstruccion() { return costoDeConstruccion; }
    public double getSalud() { return salud; }
    public void setSalud(double salud) { this.salud = salud; }

    @Override
    public String toString() {
        return "[" + id + "] " + nombre + " | Salud: " + salud + "% | Estado: " + (activo ? "Activo" : "Inactivo");
    }

    // Este método abstracto obliga a todas las clases hijas a definir su propia lógica de ciclo.
    // Aquí es donde se aplica el polimorfismo más adelante.
    public abstract String procesarCiclo(EstadoMision estado);
}