//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModuloVuelo.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




public class ModuloVuelo extends Modulo {
    private double empuje;
    private double consumoCombustiblePorCiclo;
    private double nivelCombustibleActual;
    private double capacidadTanque;

    public ModuloVuelo() {}

    public ModuloVuelo(String id, String nombre, double salud, boolean activo, double costoDeConstruccion,
                       double empuje, double consumoCombustiblePorCiclo, double nivelCombustibleActual, double capacidadTanque) {
        // 'super' llama al constructor de la clase padre Modulo para guardar los datos básicos
        super(id, nombre, salud, activo, costoDeConstruccion);
        this.empuje = empuje;
        this.consumoCombustiblePorCiclo = consumoCombustiblePorCiclo;
        this.nivelCombustibleActual = nivelCombustibleActual;
        this.capacidadTanque = capacidadTanque;
    }

    public double getEmpuje() { return empuje; }
    public double getConsumoCombustiblePorCiclo() { return consumoCombustiblePorCiclo; }
    public double getNivelCombustibleActual() { return nivelCombustibleActual; }
    public void setNivelCombustibleActual(double nivelCombustibleActual) { this.nivelCombustibleActual = nivelCombustibleActual; }
    public double getCapacidadTanque() { return capacidadTanque; }

    // Usamos Math.min para evitar rebasar el límite del tanque al recargar combustible
    public void recargarCombustible(double cantidad) {
        this.nivelCombustibleActual = Math.min(this.capacidadTanque, this.nivelCombustibleActual + cantidad);
    }

    // Sobrescribimos el método abstracto del padre con la lógica específica de este módulo
    @Override
    public String procesarCiclo(EstadoMision estado) {
        // Validamos primero si el módulo se encuentra activo para procesar el ciclo
        if (!activo) {
            return "El módulo de vuelo [" + nombre + "] está inactivo.";
        }
        
        // Verificamos si hay suficiente combustible local para operar
        if (nivelCombustibleActual >= consumoCombustiblePorCiclo) {
            nivelCombustibleActual -= consumoCombustiblePorCiclo;
            double avance = empuje * 1.5;
            
            // Math.max evita que la distancia restante en el estado global pase a números negativos
            double nuevaDistancia = Math.max(0, estado.getDistanciaRestanteAlObjetivo() - avance);
            estado.setDistanciaRestanteAlObjetivo(nuevaDistancia);
            
            return "Módulo de Vuelo [" + nombre + "] consumió " + consumoCombustiblePorCiclo + 
                   "L de combustible y avanzó " + avance + " km hacia el objetivo.";
        } else {
            // Si el combustible no alcanza, desactivamos el módulo
            activo = false;
            return "Módulo de Vuelo [" + nombre + "] se quedó sin combustible y ha quedado inactivo.";
        }
    }
}
