//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModuloTierra.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




public class ModuloTierra extends Modulo {
    private double velocidadManejo;
    private double consumoEnergiaPorCiclo;
    private double capacidadCarga;

    public ModuloTierra() {}

    public ModuloTierra(String id, String nombre, double salud, boolean activo, double costoDeConstruccion,
                        double velocidadManejo, double consumoEnergiaPorCiclo, double capacidadCarga) {
        super(id, nombre, salud, activo, costoDeConstruccion);
        this.velocidadManejo = velocidadManejo;
        this.consumoEnergiaPorCiclo = consumoEnergiaPorCiclo;
        this.capacidadCarga = capacidadCarga;
    }

    public double getVelocidadManejo() { return velocidadManejo; }
    public double getConsumoEnergiaPorCiclo() { return consumoEnergiaPorCiclo; }
    public double getCapacidadCarga() { return capacidadCarga; }

    @Override
    public String procesarCiclo(EstadoMision estado) {
        if (!activo) {
            return "El módulo de tierra [" + nombre + "] está inactivo.";
        }

        // A diferencia del módulo de vuelo, este verifica y consume la energía de la reserva GLOBAL de la misión
        if (estado.getReservaEnergia() >= consumoEnergiaPorCiclo) {
            estado.setReservaEnergia(estado.getReservaEnergia() - consumoEnergiaPorCiclo);
            
            // Calculamos los minerales obtenidos en base a la capacidad de carga y los sumamos al total global
            double mineralObtenido = capacidadCarga * 0.1;
            estado.setMineralRecolectado(estado.getMineralRecolectado() + mineralObtenido);
            
            return "Módulo Terrestre [" + nombre + "] consumió " + consumoEnergiaPorCiclo + 
                   " unidades de energía y recolectó " + mineralObtenido + " kg de mineral.";
        } else {
            return "Módulo Terrestre [" + nombre + "] no cuenta con suficiente energía general para operar este ciclo.";
        }
    }
}
