//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SimuladorMision.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




import java.util.ArrayList;


public class SimuladorMision {
    // 1. Especificar el tipo genérico <Modulo> en la declaración del atributo
    private ArrayList<Modulo> modulos;
    private EstadoMision estado;

    public SimuladorMision(EstadoMision estadoInicial) {
        this.estado = estadoInicial;
        // 2. Especificar el tipo genérico <Modulo> al instanciar (o usar el operador diamante <>)
        this.modulos = new ArrayList<Modulo>();
    }

    public boolean agregarModulo(Modulo m) {
        if (m != null) {
            return modulos.add(m);
        }
        return false;
    }

    public String ejecutarCiclo() {
        StringBuilder reporte = new StringBuilder();
        reporte.append("--- INICIANDO CICLO DE SIMULACIÓN ---\n");

        if (modulos.isEmpty()) {
            reporte.append("No hay módulos instalados en el simulador.\n");
        } else {
            // Ahora este bucle funcionará correctamente sin errores de conversión
            for (Modulo m : modulos) {
                reporte.append(m.procesarCiclo(estado)).append("\n");
            }
        }

        return reporte.toString();
    }

    public EstadoMision getEstado() { return estado; }
    public ArrayList<Modulo> getModulos() { return modulos; }
}
