//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaConsola.java
//  @ Date : 10/3/2026
//  @ Author : 
//
//




import java.util.Scanner;

public class VistaConsola {
    private Scanner scanner;

    public VistaConsola() {
        this.scanner = new Scanner(System.in);
    }

    public int mostrarMenuPrincipal() {
        System.out.println("\n=== SIMULADOR DE MISIÓN ESPACIAL ===");
        System.out.println("1. Crear nuevo módulo");
        System.out.println("2. Ejecutar ciclo de simulación");
        System.out.println("3. Ver estado de la misión");
        System.out.println("4. Recargar combustible a un módulo de vuelo");
        System.out.println("5. Salir");
        return pedirInt("Seleccione una opción: ");
    }

    public void mostrarMensaje(String m) {
        System.out.println(m);
    }

    public String pedirString(String prompt) {
        System.out.print(prompt);
        return scanner.nextLine().trim();
    }

    // Bucle while(true) combinado con try-catch: si el usuario escribe texto en lugar de un número,
    // atrapamos la excepción NumberFormatException y evitamos que el programa se caiga.
    public double pedirDouble(String prompt) {
        while (true) {
            try {
                System.out.print(prompt);
                String line = scanner.nextLine();
                return Double.parseDouble(line);
            } catch (NumberFormatException e) {
                System.out.println("Error: Ingrese un valor numérico decimal válido.");
            }
        }
    }

    public int pedirInt(String prompt) {
        while (true) {
            try {
                System.out.print(prompt);
                String line = scanner.nextLine();
                return Integer.parseInt(line);
            } catch (NumberFormatException e) {
                System.out.println("Error: Ingrese un número entero válido.");
            }
        }
    }

    public int pedirTipoModulo() {
        System.out.println("\n--- Tipo de Módulo ---");
        System.out.println("1. Módulo de Vuelo");
        System.out.println("2. Módulo Terrestre");
        System.out.println("3. Módulo de Energía");
        return pedirInt("Seleccione el tipo: ");
    }
}
