//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Animacion.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




public class Animacion extends Trabajo {
    protected int fotogramas;

    public Animacion(String codigo, String estudio, String proyecto, double horasEstimadas, String horario, int fotogramas) {
        super(codigo, estudio, proyecto, horasEstimadas, horario);
        if (fotogramas <= 0) {
            throw new IllegalArgumentException("La cantidad de fotogramas debe ser un entero positivo.");
        }
        this.fotogramas = fotogramas;
    }

    protected double calcularHorasFacturables() {
        double horasPorFotogramas = this.fotogramas * 0.02;
        return Math.max(this.horasEstimadas, horasPorFotogramas);
    }

    @Override
    public double calcularCosto() {
        double tarifaBase = horario.equalsIgnoreCase("DIURNO") ? 60.0 : 40.0;
        double horasFacturables = Math.ceil(calcularHorasFacturables());
        return tarifaBase + (horasFacturables * 15.0);
    }

    @Override
    public int calcularTiempoEntrega() {
        return horario.equalsIgnoreCase("DIURNO") ? 24 : 36;
    }

    @Override
    public int getMaxIntentos() {
        return 3;
    }
}
