//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AnimacionPostproduccion.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




public class AnimacionPostproduccion extends Animacion {
    private double valorRecursos;

    public AnimacionPostproduccion(String codigo, String estudio, String proyecto, double horasEstimadas, String horario, int fotogramas, double valorRecursos) {
        super(codigo, estudio, proyecto, horasEstimadas, horario, fotogramas);
        this.valorRecursos = valorRecursos;
    }

    @Override
    public double calcularCosto() {
        double costoAnimacionBase = super.calcularCosto();
        double recargoComposicion = 80.0;
        double recargoRecursos = this.valorRecursos * 0.05;
        return costoAnimacionBase + recargoComposicion + recargoRecursos;
    }

    @Override
    public int calcularTiempoEntrega() {
        return super.calcularTiempoEntrega() + 12;
    }

    @Override
    public int getMaxIntentos() {
        return 2;
    }
}