//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestorFinanciero.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




public class GestorFinanciero {
    private double ingresosRegistro = 0;
    private double ingresosReintentos = 0;

    public void registrarIngresoInicial(double monto) {
        this.ingresosRegistro += monto;
    }

    public void registrarIngresoReintento(double monto) {
        this.ingresosReintentos += monto;
    }

    public double getIngresoTotal() {
        return ingresosRegistro + ingresosReintentos;
    }

    public double getIngresosRegistro() { return ingresosRegistro; }
    public double getIngresosReintentos() { return ingresosReintentos; }
}
