//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ImagenFija.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




public class ImagenFija extends Trabajo {

    public ImagenFija(String codigo, String estudio, String proyecto, double horasEstimadas, String horario) {
        super(codigo, estudio, proyecto, horasEstimadas, horario);
        if (horasEstimadas > 2.0) {
            throw new IllegalArgumentException("Las horas estimadas para Imagen Fija no pueden superar 2.");
        }
    }

    @Override
    public double calcularCosto() {
        if (horario.equalsIgnoreCase("DIURNO")) {
            return 45.0;
        } else {
            return 30.0;
        }
    }

    @Override
    public int calcularTiempoEntrega() {
        return horario.equalsIgnoreCase("DIURNO") ? 4 : 10;
    }

    @Override
    public int getMaxIntentos() {
        return 3;
    }
}