//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Lote.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




import java.util.ArrayList;
import java.util.List;

public class Lote {
    private String id;
    private Nodo nodo;
    private List<Trabajo> trabajos;
    private String estado; // "EN_PREPARACION", "EN_EJECUCION", "CERRADO"

    public Lote(String id, Nodo nodo) {
        this.id = id;
        this.nodo = nodo;
        this.trabajos = new ArrayList<>();
        this.estado = "EN_PREPARACION";
    }

    public boolean agregarTrabajo(Trabajo trabajo) {
        if (!estado.equals("EN_PREPARACION")) return false;
        
        // Validar capacidad de horas
        double horasActuales = getHorasAsignadas();
        if ((horasActuales + trabajo.getHorasEstimadas()) > nodo.getCapacidadHoras()) {
            return false;
        }
        
        // Validar compatibilidad de nodo (ej. GPU para simulaciones)
        if (!trabajo.esCompatibleConNodo(nodo)) {
            return false;
        }

        trabajos.add(trabajo);
        return true;
    }

    public boolean removerTrabajo(Trabajo trabajo) {
        if (!estado.equals("EN_PREPARACION")) return false;
        return trabajos.remove(trabajo);
    }

    public void iniciarLote() {
        if (trabajos.isEmpty()) {
            throw new IllegalStateException("No puede iniciar un lote vacío.");
        }
        this.estado = "EN_EJECUCION";
        for (Trabajo t : trabajos) {
            t.setEstado("EN_EJECUCION");
        }
    }

    public double getHorasAsignadas() {
        double total = 0;
        for (Trabajo t : trabajos) {
            total += t.getHorasEstimadas();
        }
        return total;
    }

    public double getCapacidadDisponible() {
        return nodo.getCapacidadHoras() - getHorasAsignadas();
    }

    // Getters
    public String getId() { return id; }
    public Nodo getNodo() { return nodo; }
    public String getEstado() { return estado; }
    public List<Trabajo> getTrabajos() { return trabajos; }
}
