//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        SistemaRenderGT sistema = new SistemaRenderGT();

        // Agregamos un nodo inicial de prueba
        sistema.agregarNodo(new Nodo("NOD-01", 10.0, true));

        int opcion = 0;
        do {
            System.out.println("\n=== Sistema RenderGT ===");
            System.out.println("1. Registrar Imagen Fija");
            System.out.println("2. Ver Finanzas e Ingresos");
            System.out.println("3. Salir");
            System.out.print("Seleccione una opcion: ");

            if (scanner.hasNextInt()) {
                opcion = scanner.nextInt();
                scanner.nextLine();

                switch (opcion) {
                    case 1:
                        try {
                            System.out.print("Codigo del trabajo: ");
                            String codigo = scanner.nextLine();
                            System.out.print("Estudio: ");
                            String estudio = scanner.nextLine();
                            System.out.print("Proyecto: ");
                            String proyecto = scanner.nextLine();
                            System.out.print("Horas estimadas (max 2): ");
                            double horas = scanner.nextDouble();
                            scanner.nextLine();
                            System.out.print("Horario (DIURNO / NOCTURNO): ");
                            String horario = scanner.nextLine();

                            ImagenFija img = new ImagenFija(codigo, estudio, proyecto, horas, horario);
                            sistema.registrarTrabajo(img);

                            System.out.println("¡Trabajo registrado con éxito!");
                            System.out.println("Costo cobrado: Q" + img.calcularCosto());
                        } catch (Exception e) {
                            System.out.println("Error: " + e.getMessage());
                        }
                        break;

                    case 2:
                        GestorFinanciero finanzas = sistema.getGestorFinanciero();
                        System.out.println("\n--- Reporte Financiero ---");
                        System.out.println("Ingresos Totales: Q" + finanzas.getIngresoTotal());
                        System.out.println("Total trabajos en sistema: " + sistema.getTrabajos().size());
                        break;

                    case 3:
                        System.out.println("Saliendo...");
                        break;

                    default:
                        System.out.println("Opción no válida.");
                }
            } else {
                scanner.next();
                opcion = 0;
            }
        } while (opcion != 3);

        scanner.close();
    }
}