//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nodo.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




public class Nodo {
    private String codigo;
    private double capacidadHoras;
    private boolean tieneGPU;
    private boolean libre;

    public Nodo(String codigo, double capacidadHoras, boolean tieneGPU) {
        this.codigo = codigo;
        this.capacidadHoras = capacidadHoras;
        this.tieneGPU = tieneGPU;
        this.libre = true;
    }

    public String getCodigo() { return codigo; }
    public double getCapacidadHoras() { return capacidadHoras; }
    public boolean tieneGPU() { return tieneGPU; }
    public boolean isLibre() { return libre; }
    public void setLibre(boolean libre) { this.libre = libre; }
}
