//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SimulacionFisica.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




public class SimulacionFisica extends Trabajo {
    private int resolucionMalla; // en millones de celdas (1 a 50)

    public SimulacionFisica(String codigo, String estudio, String proyecto, double horasEstimadas, String horario, int resolucionMalla) {
        super(codigo, estudio, proyecto, horasEstimadas, horario);
        if (resolucionMalla < 1 || resolucionMalla > 50) {
            throw new IllegalArgumentException("La resolución de la malla debe estar entre 1 y 50 millones.");
        }
        if (horario.equalsIgnoreCase("DIURNO")) {
            throw new IllegalArgumentException("Las simulaciones físicas solo se aceptan en horario nocturno.");
        }
        this.resolucionMalla = resolucionMalla;
    }

    @Override
    public double calcularCosto() {
        double tarifaBaseNocturna = 40.0; // Tarifa base nocturna base
        double costoHoras = this.horasEstimadas * 22.0;
        double cargoGPU = 65.0;
        return tarifaBaseNocturna + costoHoras + cargoGPU;
    }

    @Override
    public int calcularTiempoEntrega() {
        return 18; // Siempre 18 horas
    }

    @Override
    public int getMaxIntentos() {
        return 1; // 1 solo intento
    }

    @Override
    public boolean esCompatibleConNodo(Nodo nodo) {
        // Exige estrictamente que el nodo tenga GPU
        return nodo.tieneGPU();
    }
}
