//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SistemaRenderGT.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




import java.util.ArrayList;
import java.util.List;

public class SistemaRenderGT {
    private List<Trabajo> trabajos;
    private List<Nodo> nodos;
    private List<Lote> lotes;
    private GestorFinanciero gestorFinanciero;

    public SistemaRenderGT() {
        this.trabajos = new ArrayList<>();
        this.nodos = new ArrayList<>();
        this.lotes = new ArrayList<>();
        this.gestorFinanciero = new GestorFinanciero();
    }

    // Método para registrar un trabajo y cobrar automáticamente
    public void registrarTrabajo(Trabajo trabajo) {
        trabajos.add(trabajo);
        double costo = trabajo.calcularCosto();
        gestorFinanciero.registrarIngresoInicial(costo);
    }

    // Método para agregar un nodo al sistema
    public void agregarNodo(Nodo nodo) {
        nodos.add(nodo);
    }

    // Método para crear un lote
    public Lote crearLote(String idLote, String codigoNodo) {
        Nodo nodoEncontrado = null;
        for (Nodo n : nodos) {
            if (n.getCodigo().equalsIgnoreCase(codigoNodo)) {
                nodoEncontrado = n;
                break;
            }
        }
        
        if (nodoEncontrado != null && nodoEncontrado.isLibre()) {
            Lote nuevoLote = new Lote(idLote, nodoEncontrado);
            lotes.add(nuevoLote);
            nodoEncontrado.setLibre(false);
            return nuevoLote;
        }
        return null; // Nodo no encontrado o ocupado
    }

    // Getters para reportes
    public GestorFinanciero getGestorFinanciero() {
        return gestorFinanciero;
    }

    public List<Trabajo> getTrabajos() {
        return trabajos;
    }

    public List<Lote> getLotes() {
        return lotes;
    }
}