//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Trabajo.java
//  @ Date : 10/10/2026
//  @ Author : 
//
//




public abstract class Trabajo {
    protected String codigo;
    protected String estudio;
    protected String proyecto;
    protected double horasEstimadas;
    protected String horario; // "DIURNO" o "NOCTURNO"
    protected String estado;  // "EN_COLA", "EN_EJECUCION", "COMPLETADO", "CANCELADO"
    protected int intentos;

    public Trabajo(String codigo, String estudio, String proyecto, double horasEstimadas, String horario) {
        this.codigo = codigo;
        this.estudio = estudio;
        this.proyecto = proyecto;
        this.horasEstimadas = horasEstimadas;
        this.horario = horario;
        this.estado = "EN_COLA";
        this.intentos = 0;
    }

    public abstract double calcularCosto();
    public abstract int calcularTiempoEntrega();
    public abstract int getMaxIntentos();

    public boolean esCompatibleConNodo(Nodo nodo) {
        // Por defecto cualquier trabajo es compatible con cualquier nodo
        return true;
    }

    public void registrarIntento() {
        this.intentos++;
    }

    // Getters y Setters básicos
    public String getCodigo() { return codigo; }
    public String getEstado() { return estado; }
    public void setEstado(String estado) { this.estado = estado; }
    public int getIntentos() { return intentos; }
    public double getHorasEstimadas() { return horasEstimadas; }
    public String getHorario() { return horario; }
    public String getEstudio() { return estudio; }
    public String getProyecto() { return proyecto; }
}
