//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Caso.java
//  @ Date : 9/2/2026
//  @ Author : 
//
//




import java.util.ArrayList;

public class Caso {
    private String nombreCaso;
    private String codIdentificacion;
    private String detective;
    private Ubicacion[] lugares;
    private ArrayList<Pista> pistas;

    public Caso(String nombreCaso, String codIdentificacion, String detective) {
        this.nombreCaso = nombreCaso;
        this.codIdentificacion = codIdentificacion;
        this.detective = detective;
        this.lugares = new Ubicacion[5];
        this.pistas = new ArrayList<>();
    }

    // Métodos de Ubicación
    public int cantidadUbicaciones() {
        int contador = 0;
        for (Ubicacion u : lugares) {
            if (u != null) {
                contador++;
            }
        }
        return contador;
    }

    public int disponibilidadUbicaciones() {
        return 5 - cantidadUbicaciones();
    }

    public Ubicacion ubiConMayorRiesgo() {
        Ubicacion mayor = null;
        for (Ubicacion u : lugares) {
            if (u != null) {
                if (mayor == null || u.getNivelRiesgo() > mayor.getNivelRiesgo()) {
                    mayor = u;
                }
            }
        }
        return mayor;
    }

    public void registrarUbicacion(int posicion, int newCodigo, String newNombre, String newDireccion, int newNivelRiesgo, String newEstado) {
        if (posicion >= 0 && posicion < lugares.length) {
            lugares[posicion] = new Ubicacion(newNombre, newCodigo, newDireccion, newNivelRiesgo, newEstado);
        }
    }

    public void modificarUbicacion(int posicion, int nuevoRiesgo, String nuevoEstado) {
        if (posicion >= 0 && posicion < lugares.length && lugares[posicion] != null) {
            lugares[posicion].setNivelRiesgo(nuevoRiesgo);
            lugares[posicion].setEstado(nuevoEstado);
        }
    }

    public void descartarUbicacion(int posicion) {
        if (posicion >= 0 && posicion < lugares.length) {
            lugares[posicion] = null;
        }
    }

    public Ubicacion[] consultarUbicaciones() {
        return lugares;
    }

    // Métodos de Pista
    public int cantidadPistasRegistradas() {
        return pistas.size();
    }

    public void ingresarPista(Pista pista) {
        if (pista != null) {
            pistas.add(pista);
        }
    }

    public ArrayList<Pista> consultarPistas() {
        return pistas;
    }

    public Pista buscarPista(String codigoPista) {
        for (Pista p : pistas) {
            if (p.getCodigoPista().equalsIgnoreCase(codigoPista)) {
                return p;
            }
        }
        return null;
    }

    public void modificarPista(String codigoPista, int newNivelImportncia, int newNivelConfiabilidad) {
        Pista p = buscarPista(codigoPista);
        if (p != null) {
            p.setNivelImportancia(newNivelImportncia);
            p.setNivelConfiabilidad(newNivelConfiabilidad);
        }
    }

    public void eliminarPista(String codigoPista) {
        Pista p = buscarPista(codigoPista);
        if (p != null) {
            pistas.remove(p);
        }
    }

    // Métodos de Reporte
    public Pista pistaConMayorConfiabilidad() {
        if (pistas.isEmpty()) return null;
        Pista mayor = pistas.get(0);
        for (Pista p : pistas) {
            if (p.getNivelConfiabilidad() > mayor.getNivelConfiabilidad()) {
                mayor = p;
            }
        }
        return mayor;
    }

    public Pista pistaConMayorImportancia() {
        if (pistas.isEmpty()) return null;
        Pista mayor = pistas.get(0);
        for (Pista p : pistas) {
            if (p.getNivelImportancia() > mayor.getNivelImportancia()) {
                mayor = p;
            }
        }
        return mayor;
    }

    public double promedioNivelImportancia() {
        if (pistas.isEmpty()) return 0.0;
        double suma = 0;
        for (Pista p : pistas) {
            suma += p.getNivelImportancia();
        }
        return suma / pistas.size();
    }
}
