//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 9/2/2026
//  @ Author : 
//
//




import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

public class Main {
    private static Scanner scanner = new Scanner(System.in);
    private static Caso casoActual = null;

    public static void main(String[] args) {
        int opcion = -1;

        do {
            try {
                mostrarMenu();
                opcion = scanner.nextInt();
                scanner.nextLine(); // Limpiar búfer

                switch (opcion) {
                    case 1:
                        crearNuevoCaso();
                        break;
                    case 2:
                        registrarUbicacion();
                        break;
                    case 3:
                        modificarUbicacion();
                        break;
                    case 4:
                        descartarUbicacion();
                        break;
                    case 5:
                        consultarUbicaciones();
                        break;
                    case 6:
                        ingresarPista();
                        break;
                    case 7:
                        modificarPista();
                        break;
                    case 8:
                        consultarPistas();
                        break;
                    case 9:
                        eliminarPista();
                        break;
                    case 10:
                        mostrarReportes();
                        break;
                    case 0:
                        System.out.println("\nSaliendo del sistema de la Agencia de Detectives...");
                        break;
                    default:
                        System.out.println("Opción inválida. Intente de nuevo.");
                }
            } catch (InputMismatchException e) {
                System.out.println("Error: Debe ingresar un número entero válido.");
                scanner.nextLine(); // Limpiar entrada errónea
            } catch (Exception e) {
                System.out.println("Ocurrió un error inesperado: " + e.getMessage());
            } finally {
                System.out.println(); // Línea en blanco para ordenar la consola
            }
        } while (opcion != 0);

        scanner.close();
    }

    private static void mostrarMenu() {
        System.out.println("=== AGENCIA DE DETECTIVES - CASO MISTERIOSO ===");
        System.out.println("1. Crear nuevo caso");
        System.out.println("2. Registrar ubicación");
        System.out.println("3. Modificar nivel de riesgo y estado de ubicación");
        System.out.println("4. Descartar ubicación");
        System.out.println("5. Consultar ubicaciones registradas");
        System.out.println("6. Ingresar pista encontrada");
        System.out.println("7. Modificar nivel de importancia y confiabilidad de una pista");
        System.out.println("8. Consultar pistas registradas");
        System.out.println("9. Eliminar pista");
        System.out.println("10. Generar reporte estadístico del caso");
        System.out.println("0. Salir");
        System.out.print("Seleccione una opción: ");
    }

    private static void crearNuevoCaso() {
        System.out.println("\n--- CREAR NUEVO CASO ---");
        System.out.print("Nombre del caso: ");
        String nombre = scanner.nextLine();
        System.out.print("Código de identificación: ");
        String codigo = scanner.nextLine();
        System.out.print("Nombre del detective a cargo: ");
        String detective = scanner.nextLine();

        casoActual = new Caso(nombre, codigo, detective);
        System.out.println("¡Caso '" + nombre + "' creado exitosamente!");
    }

    private static void registrarUbicacion() {
        if (!validarCasoExiste()) return;

        if (casoActual.disponibilidadUbicaciones() == 0) {
            System.out.println("Error: Ya se han registrado las 5 ubicaciones máximas para este caso.");
            return;
        }

        System.out.println("\n--- REGISTRAR UBICACIÓN ---");
        System.out.print("Ingrese la posición en el arreglo (0 a 4): ");
        int pos = scanner.nextInt();
        scanner.nextLine();

        if (pos < 0 || pos >= 5) {
            System.out.println("Error: Posición fuera del rango (0-4).");
            return;
        }

        System.out.print("Código de la ubicación (número): ");
        int codigo = scanner.nextInt();
        scanner.nextLine();

        System.out.print("Nombre de la ubicación: ");
        String nombre = scanner.nextLine();

        System.out.print("Dirección: ");
        String direccion = scanner.nextLine();

        System.out.print("Nivel de riesgo (1 a 10): ");
        int riesgo = scanner.nextInt();
        scanner.nextLine();

        if (riesgo < 1 || riesgo > 10) {
            System.out.println("Error: El nivel de riesgo debe estar entre 1 y 10.");
            return;
        }

        System.out.print("Estado de la ubicación: ");
        String estado = scanner.nextLine();

        casoActual.registrarUbicacion(pos, codigo, nombre, direccion, riesgo, estado);
        System.out.println("Ubicación registrada exitosamente en la posición " + pos + ".");
    }

    private static void modificarUbicacion() {
        if (!validarCasoExiste()) return;

        System.out.println("\n--- MODIFICAR UBICACIÓN ---");
        System.out.print("Ingrese la posición a modificar (0 a 4): ");
        int pos = scanner.nextInt();
        scanner.nextLine();

        System.out.print("Nuevo nivel de riesgo (1 a 10): ");
        int riesgo = scanner.nextInt();
        scanner.nextLine();

        if (riesgo < 1 || riesgo > 10) {
            System.out.println("Error: El nivel de riesgo debe estar entre 1 y 10.");
            return;
        }

        System.out.print("Nuevo estado: ");
        String estado = scanner.nextLine();

        casoActual.modificarUbicacion(pos, riesgo, estado);
        System.out.println("Ubicación en posición " + pos + " modificada correctamente.");
    }

    private static void descartarUbicacion() {
        if (!validarCasoExiste()) return;

        System.out.println("\n--- DESCARTAR UBICACIÓN ---");
        System.out.print("Ingrese la posición a descartar (0 a 4): ");
        int pos = scanner.nextInt();
        scanner.nextLine();

        casoActual.descartarUbicacion(pos);
        System.out.println("Ubicación en posición " + pos + " descartada.");
    }

    private static void consultarUbicaciones() {
        if (!validarCasoExiste()) return;

        System.out.println("\n--- UBICACIONES DEL CASO ---");
        Ubicacion[] lista = casoActual.consultarUbicaciones();
        boolean hayUbicaciones = false;

        for (int i = 0; i < lista.length; i++) {
            if (lista[i] != null) {
                hayUbicaciones = true;
                System.out.println("Posición [" + i + "]: " + lista[i].getNombreUbi() + " (Código: " + lista[i].getCodigoUbi() + ") | Riesgo: " + lista[i].getNivelRiesgo() + " | Estado: " + lista[i].getEstado() + " | Dirección: " + lista[i].getDireccion());
            } else {
                System.out.println("Posición [" + i + "]: [Vacía]");
            }
        }

        if (!hayUbicaciones) {
            System.out.println("No hay ubicaciones actualmente en el sistema.");
        }
    }

    private static void ingresarPista() {
        if (!validarCasoExiste()) return;

        System.out.println("\n--- INGRESAR PISTA ---");
        System.out.print("Código de la pista: ");
        String codigo = scanner.nextLine();

        System.out.print("Descripción: ");
        String desc = scanner.nextLine();

        System.out.print("Tipo de evidencia: ");
        String tipo = scanner.nextLine();

        System.out.print("Nivel de importancia (1 a 10): ");
        int imp = scanner.nextInt();
        scanner.nextLine();

        if (imp < 1 || imp > 10) {
            System.out.println("Error: La importancia debe estar entre 1 y 10.");
            return;
        }

        System.out.print("Nivel de confiabilidad (0 a 100): ");
        int conf = scanner.nextInt();
        scanner.nextLine();

        if (conf < 0 || conf > 100) {
            System.out.println("Error: La confiabilidad debe estar entre 0 y 100.");
            return;
        }

        Pista nuevaPista = new Pista(codigo, desc, tipo, imp, conf);
        casoActual.ingresarPista(nuevaPista);
        System.out.println("Pista ingresada exitosamente.");
    }

    private static void modificarPista() {
        if (!validarCasoExiste()) return;

        System.out.println("\n--- MODIFICAR PISTA ---");
        System.out.print("Ingrese el código de la pista a modificar: ");
        String codigo = scanner.nextLine();

        Pista p = casoActual.buscarPista(codigo);
        if (p == null) {
            System.out.println("Error: Pista no encontrada.");
            return;
        }

        System.out.print("Nuevo nivel de importancia (1 a 10): ");
        int imp = scanner.nextInt();
        scanner.nextLine();

        if (imp < 1 || imp > 10) {
            System.out.println("Error: La importancia debe estar entre 1 y 10.");
            return;
        }

        System.out.print("Nuevo nivel de confiabilidad (0 a 100): ");
        int conf = scanner.nextInt();
        scanner.nextLine();

        if (conf < 0 || conf > 100) {
            System.out.println("Error: La confiabilidad debe estar entre 0 y 100.");
            return;
        }

        casoActual.modificarPista(codigo, imp, conf);
        System.out.println("Pista modificada correctamente.");
    }

    private static void consultarPistas() {
        if (!validarCasoExiste()) return;

        System.out.println("\n--- PISTAS REGISTRADAS ---");
        ArrayList<Pista> lista = casoActual.consultarPistas();

        if (lista.isEmpty()) {
            System.out.println("No hay pistas registradas.");
            return;
        }

        for (Pista p : lista) {
            System.out.println("Código: " + p.getCodigoPista() + " | Tipo: " + p.getTipoEvidencia() + " | Importancia: " + p.getNivelImportancia() + " | Confiabilidad: " + p.getNivelConfiabilidad() + "% | Desc: " + p.getDescripcion());
        }
    }

    private static void eliminarPista() {
        if (!validarCasoExiste()) return;

        System.out.println("\n--- ELIMINAR PISTA ---");
        System.out.print("Ingrese el código de la pista a eliminar: ");
        String codigo = scanner.nextLine();

        casoActual.eliminarPista(codigo);
        System.out.println("Operación de eliminación completada.");
    }

    private static void mostrarReportes() {
        if (!validarCasoExiste()) return;

        System.out.println("\n=== REPORTE ESTADÍSTICO DEL CASO ===");
        System.out.println("Ubicaciones ocupadas: " + casoActual.cantidadUbicaciones() + " de 5");
        System.out.println("Ubicaciones disponibles: " + casoActual.disponibilidadUbicaciones());

        Ubicacion mayorRiesgo = casoActual.ubiConMayorRiesgo();
        if (mayorRiesgo != null) {
            System.out.println("Ubicación de mayor riesgo: " + mayorRiesgo.getNombreUbi() + " (Riesgo: " + mayorRiesgo.getNivelRiesgo() + ")");
        } else {
            System.out.println("Ubicación de mayor riesgo: [Sin ubicaciones registradas]");
        }

        System.out.println("------------------------------------");
        System.out.println("Total de pistas encontradas: " + casoActual.cantidadPistasRegistradas());

        Pista mayorConf = casoActual.pistaConMayorConfiabilidad();
        if (mayorConf != null) {
            System.out.println("Pista con mayor confiabilidad: " + mayorConf.getCodigoPista() + " (" + mayorConf.getNivelConfiabilidad() + "%)");
        } else {
            System.out.println("Pista con mayor confiabilidad: [Sin pistas registradas]");
        }

        Pista mayorImp = casoActual.pistaConMayorImportancia();
        if (mayorImp != null) {
            System.out.println("Pista con mayor importancia: " + mayorImp.getCodigoPista() + " (Nivel " + mayorImp.getNivelImportancia() + ")");
        } else {
            System.out.println("Pista con mayor importancia: [Sin pistas registradas]");
        }

        System.out.printf("Promedio de importancia de las pistas: %.2f\n", casoActual.promedioNivelImportancia());
    }

    private static boolean validarCasoExiste() {
        if (casoActual == null) {
            System.out.println("Error: Primero debe crear un caso (Opción 1).");
            return false;
        }
        return true;
    }
}
