//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pista.java
//  @ Date : 9/2/2026
//  @ Author : 
//
//




public class Pista {
    private String codigoPista;
    private String descripcion;
    private String tipoEvidencia;
    private int nivelImportancia;
    private int nivelConfiabilidad;

    public Pista(String codigoPista, String descripcion, String tipoEvidencia, int nivelImportancia, int nivelConfiabilidad) {
        this.codigoPista = codigoPista;
        this.descripcion = descripcion;
        this.tipoEvidencia = tipoEvidencia;
        this.nivelImportancia = nivelImportancia;
        this.nivelConfiabilidad = nivelConfiabilidad;
    }

    public String getCodigoPista() {
        return codigoPista;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public String getTipoEvidencia() {
        return tipoEvidencia;
    }

    public int getNivelImportancia() {
        return nivelImportancia;
    }

    public int getNivelConfiabilidad() {
        return nivelConfiabilidad;
    }

    public void setNivelImportancia(int nivel) {
        this.nivelImportancia = nivel;
    }

    public void setNivelConfiabilidad(int nivel) {
        this.nivelConfiabilidad = nivel;
    }
}
