//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ubicacion.java
//  @ Date : 9/2/2026
//  @ Author : 
//
//




public class Ubicacion {
	private String nombre;
	private int codigo;
	private String direccion;
	private int nivelRiesgo;
	private String estado;


	public Ubicacion(String nombre, int codigo, String direccion, int nivelRiesgo, String estado) {
        this.nombre = nombre;
        this.codigo = codigo;
        this.direccion = direccion;
        this.nivelRiesgo = nivelRiesgo;
        this.estado = estado;
    }

    public String getNombreUbi() {
        return nombre;
    }

    public int getCodigoUbi() {
        return codigo;
    }

    public String getDireccion() {
        return direccion;
    }

    public int getNivelRiesgo() {
        return nivelRiesgo;
    }

    public String getEstado() {
        return estado;
    }

    public void setNivelRiesgo(int nuevoRiesgo) {
        this.nivelRiesgo = nuevoRiesgo;
    }

    public void setEstado(String nuevoEstado) {
        this.estado = nuevoEstado;
    }
}
