//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DulceEstacion.java
//  @ Date : 9/26/2026
//  @ Author : 
//
//

import java.util.ArrayList;

public class DulceEstacion {
    private ArrayList inventario;
    private double ingresosAcumulados;

    public DulceEstacion() {
        this.inventario = new ArrayList<>();
        this.ingresosAcumulados = 0.0;
    }

    public boolean agregarMaquina(Maquina newMaquina) {
        if (buscarMaquina(newMaquina.getCodigo()) != null) {
            return false;
        }
        inventario.add(newMaquina);
        return true;
    }

    public Maquina buscarMaquina(String codigo) {
        // Recorrido con casteo explícito para resolver cualquier error de Object a Maquina
        for (Object obj : inventario) {
            Maquina m = (Maquina) obj;
            if (m.getCodigo().equalsIgnoreCase(codigo)) {
                return m;
            }
        }
        return null;
    }

    public String cotizar(String codigo, int dias) {
        Maquina m = buscarMaquina(codigo);
        if (m == null) {
            return "Error: No se encontró la máquina con código " + codigo;
        }
        double costoTotal = m.calcularCostoAlquiler(dias);
        return "--- COTIZACIÓN --- \n" + m.getDetalles() + "\nDías: " + dias + " | Costo Total: Q" + costoTotal;
    }

    public boolean alquilarMaquina(String codigo, int dias) {
        Maquina m = buscarMaquina(codigo);
        if (m != null && m.estaDisponible()) {
            double costoTotal = m.calcularCostoAlquiler(dias);
            m.setDisponibilidad(false);
            ingresosAcumulados += costoTotal;
            return true;
        }
        return false;
    }

    public boolean devolverMaquina(String codigo) {
        Maquina m = buscarMaquina(codigo);
        if (m != null && !m.estaDisponible()) {
            m.setDisponibilidad(true);
            return true;
        }
        return false;
    }

    public String generarReporteJornada() {
        String reporte = "=== REPORTE DE LA JORNADA ===\n";
        reporte += "Ingresos Totales Acumulados: Q" + ingresosAcumulados + "\n\n";
        reporte += "ESTADO DEL INVENTARIO:\n";

        if (inventario.isEmpty()) {
            reporte += "No hay máquinas registradas en el inventario.";
        } else {
            for (Object obj : inventario) {
                Maquina m = (Maquina) obj;
                reporte += m.getDetalles() + "\n";
            }
        }
        return reporte;
    }

    public double getIngresosAcumulados() {
        return ingresosAcumulados;
    }
}
