//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FuenteChocolate.java
//  @ Date : 9/26/2026
//  @ Author : 
//
//




public class FuenteChocolate extends Maquina {
	private double kilogramoDeCapacidad;


	public FuenteChocolate(String codigo, String marca, String modelo, double tarifaDiaria, double kilogramoDeCapacidad) {
		super(codigo, marca, modelo, tarifaDiaria);
		this.kilogramoDeCapacidad = kilogramoDeCapacidad;
	}
	
	@Override 
	public double calcularCostoAlquiler(int dias) {
		double costoDeKg = 20*kilogramoDeCapacidad*dias;
		double costoBase = tarifaDiaria*dias;
		double costoTotal = costoBase + costoDeKg;
		return costoTotal;

	}

	public double getKilogramoDeCapacidad(){
		return kilogramoDeCapacidad;
	}

	@Override 
	public String getDetalles(){
		return super.getDetalles() + " | Capacidad Max: " + kilogramoDeCapacidad + " kg";
	}
	
}
