//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 9/26/2026
//  @ Author : 
//
//




import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        DulceEstacion empresa = new DulceEstacion();
        Scanner scanner = new Scanner(System.in);
        int opcion = 0;

        do {
            System.out.println("\n--- DULCE ESTACIÓN - MENÚ PRINCIPAL ---");
            System.out.println("1. Registrar Máquina");
            System.out.println("2. Cotizar Alquiler");
            System.out.println("3. Alquilar Máquina");
            System.out.println("4. Devolver Máquina");
            System.out.println("5. Generar Reporte de la Jornada");
            System.out.println("6. Salir");
            System.out.print("Seleccione una opción: ");

            try {
                opcion = Integer.parseInt(scanner.nextLine());
            } catch (NumberFormatException e) {
                System.out.println("Por favor, ingrese un número válido.");
                continue;
            }

            switch (opcion) {
                case 1:
                    registrarMaquinaMenu(empresa, scanner);
                    break;

                case 2:
                    System.out.print("Ingrese el código de la máquina: ");
                    String codCotizar = scanner.nextLine();
                    System.out.print("Ingrese la cantidad de días: ");
                    int diasCotizar = Integer.parseInt(scanner.nextLine());
                    System.out.println(empresa.cotizar(codCotizar, diasCotizar));
                    break;

                case 3:
                    System.out.print("Ingrese el código de la máquina a alquilar: ");
                    String codAlquilar = scanner.nextLine();
                    System.out.print("Ingrese los días de alquiler: ");
                    int diasAlquilar = Integer.parseInt(scanner.nextLine());

                    if (empresa.alquilarMaquina(codAlquilar, diasAlquilar)) {
                        System.out.println("¡Máquina alquilada exitosamente!");
                    } else {
                        System.out.println("No se pudo alquilar. Verifique el código o la disponibilidad.");
                    }
                    break;

                case 4:
                    System.out.print("Ingrese el código de la máquina a devolver: ");
                    String codDevolver = scanner.nextLine();

                    if (empresa.devolverMaquina(codDevolver)) {
                        System.out.println("¡Máquina devuelta e ingresada nuevamente al inventario!");
                    } else {
                        System.out.println("No se pudo devolver. Verifique si el código existe y está actualmente alquilada.");
                    }
                    break;

                case 5:
                    System.out.println(empresa.generarReporteJornada());
                    break;

                case 6:
                    System.out.println("¡Saliendo del programa!");
                    break;

                default:
                    System.out.println("Opción no válida.");
            }
        } while (opcion != 6);

        scanner.close();
    }

    private static void registrarMaquinaMenu(DulceEstacion empresa, Scanner scanner) {
        System.out.println("\n--- TIPO DE MÁQUINA A REGISTRAR ---");
        System.out.println("1. Fuente de Chocolate");
        System.out.println("2. Máquina de Algodón");
        System.out.println("3. Máquina de Poporopos");
        System.out.print("Seleccione una opción: ");
        int tipo = Integer.parseInt(scanner.nextLine());

        System.out.print("Código: ");
        String codigo = scanner.nextLine();
        System.out.print("Marca: ");
        String marca = scanner.nextLine();
        System.out.print("Modelo: ");
        String modelo = scanner.nextLine();
        System.out.print("Tarifa Diaria: Q");
        double tarifa = Double.parseDouble(scanner.nextLine());

        Maquina nueva = null;

        switch (tipo) {
            case 1:
                System.out.print("Capacidad en Kg: ");
                double kg = Double.parseDouble(scanner.nextLine());
                nueva = new FuenteChocolate(codigo, marca, modelo, tarifa, kg);
                break;
            case 2:
                System.out.print("Potencia en Vatios (W): ");
                int vatios = Integer.parseInt(scanner.nextLine());
                nueva = new MaquinaAlgodon(codigo, marca, modelo, tarifa, vatios);
                break;
            case 3:
                System.out.print("Porciones por hora: ");
                int porciones = Integer.parseInt(scanner.nextLine());
                System.out.print("¿Tiene carrito? (true/false): ");
                boolean carrito = Boolean.parseBoolean(scanner.nextLine());
                nueva = new MaquinaPoporopos(codigo, marca, modelo, tarifa, porciones, carrito);
                break;
            default:
                System.out.println("Tipo no válido.");
                return;
        }

        if (empresa.agregarMaquina(nueva)) {
            System.out.println("¡Máquina agregada con éxito!");
        } else {
            System.out.println("Error: Ya existe una máquina registrada con ese código.");
        }
    }
}
