//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaquinaAlgodon.java
//  @ Date : 9/26/2026
//  @ Author : 
//
//




public class MaquinaAlgodon extends Maquina {
	private int potenciaDeVatios;


	public MaquinaAlgodon(String codigo, String marca, String modelo, double tarifaDiaria, int potenciaDeVatios) {
		super(codigo, marca, modelo, tarifaDiaria);
		this.potenciaDeVatios = potenciaDeVatios;
	}
	
	@Override 
	public double calcularCostoAlquiler(int dias) {
		double costoBase = tarifaDiaria*dias;
		if(potenciaDeVatios > 1000){
			double costoNuevo = costoBase + 60;
			return costoNuevo;
		}

		return costoBase;
	}
	
	public int getPotenciaVatios(){
		return potenciaDeVatios;
	}

	@Override 
	public String getDetalles(){
		return super.getDetalles() + " | Potencia: " + potenciaDeVatios + "W";
	}
	
}
