//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Maquina.java
//  @ Date : 9/26/2026
//  @ Author : 
//
//




public abstract class Maquina {
	protected String codigo;
	protected String marca;
	protected String modelo;
	protected double tarifaDiaria;
	protected boolean disponible;


	public Maquina(String codigo, String marca, String modelo, double tarifaDiaria) {
		this.codigo = codigo;
		this.marca = marca;
		this.modelo = modelo;
		this.tarifaDiaria= tarifaDiaria;
		this.disponible = true;
	}
	
	public abstract double calcularCostoAlquiler(int dias);
	
	public String getCodigo() {
		return this.codigo;
	}
	
	public boolean estaDisponible() {
		return this.disponible;
	}
	
	public void setDisponibilidad(boolean disponible) {
		this.disponible = disponible;
	}

	public String getDetalles() {
		return "Código: " + codigo + " | Estado: " + (disponible ? "Disponible" : "Alquilada");
	}
	
}
