//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaquinaPoporopos.java
//  @ Date : 9/26/2026
//  @ Author : 
//
//




public class MaquinaPoporopos extends Maquina {
	private boolean tieneCarrito;
	private int porcionPorHora;


	public MaquinaPoporopos(String codigo, String marca, String modelo, double tarifaDiaria, int porcionPorHora, boolean tieneCarrito) {
		super(codigo, marca, modelo, tarifaDiaria);
		this.tieneCarrito = tieneCarrito;
		this.porcionPorHora = porcionPorHora;
	}
	
	@Override 
	public double calcularCostoAlquiler(int dias) {
		double costoNormal = tarifaDiaria*dias;
		if(tieneCarrito == true){
			double costoAdicional = 40*dias;
			double costoTotal = costoNormal + costoAdicional;

			return costoTotal;
		}
		return costoNormal;
	}


	public int getPorciones(){
		return porcionPorHora;
	}

	public boolean isCarrito(){
		return tieneCarrito;
	}



	@Override 
	public String getDetalles(){
		return super.getDetalles() + "Porciones por hora: " + getPorciones() + " | Carrito: " + (tieneCarrito ? "Si" : "No");
	}
	
}