//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 8/12/2026
//  @ Author : 
//
//
import java.util.Scanner;

public class Principal {
    private static Usuario usuarioActivo;
    private static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("=== SISTEMA DE CALIFICACIONES DE PELÍCULAS ===");
        crearNuevoUsuario();

        boolean continuarEjecutando = true;

        while (continuarEjecutando) {
            mostrarMenu();
            System.out.print("Seleccione una opción: ");

            if (scanner.hasNextInt()) {
                int opcion = scanner.nextInt();
                scanner.nextLine();

                if (opcion == 1) {
                    crearNuevoUsuario();
                } else if (opcion == 2) {
                    registrarCalificacion();
                } else if (opcion == 3) {
                    consultarCalificaciones();
                } else if (opcion == 4) {
                    consultarUnaPelicula();
                } else if (opcion == 5) {
                    modificarCalificacion();
                } else if (opcion == 6) {
                    mostrarPromedio();
                } else if (opcion == 7) {
                    mostrarMejorYPeor();
                } else if (opcion == 8) {
                    consultarEspacios();
                } else if (opcion == 9) {
                    System.out.println("¡Gracias por utilizar el sistema!");
                    continuarEjecutando = false;
                } else {
                    System.out.println("Opción no válida. Intente nuevamente.");
                }
            } else {
                System.out.println("Por favor, ingrese un número entero válido.");
                scanner.nextLine();
            }
            System.out.println();
        }
    }

    private static void mostrarMenu() {
        System.out.println("\n--- MENÚ PRINCIPAL ---");
        System.out.println("1. Nuevo usuario");
        System.out.println("2. Registrar nueva calificación");
        System.out.println("3. Consultar calificaciones");
        System.out.println("4. Consultar una película");
        System.out.println("5. Modificar calificación");
        System.out.println("6. Mostrar promedio");
        System.out.println("7. Mostrar mejor y peor calificación");
        System.out.println("8. Consultar espacios disponibles");
        System.out.println("9. Salir");
    }

    private static void crearNuevoUsuario() {
        System.out.println("\n--- Ingreso de Datos del Usuario ---");
        System.out.print("Nombre: ");
        String nombre = scanner.nextLine();
        
        System.out.print("Nombre de usuario: ");
        String usuario = scanner.nextLine();
        
        System.out.print("Edad: ");
        while (!scanner.hasNextInt()) {
            System.out.print("Error. Ingrese un número para la edad: ");
            scanner.nextLine();
        }
        int edad = scanner.nextInt();
        scanner.nextLine();

        // Se usa tu constructor de Usuario
        usuarioActivo = new Usuario(nombre, usuario, edad);
        System.out.println("¡Usuario " + usuarioActivo.getNombre() + " registrado exitosamente!");
    }

    private static void registrarCalificacion() {
        // Llama a tu método disponibilidad()
        if (!usuarioActivo.disponibilidad()) {
            System.out.println("Error: Ya se han alcanzado las 10 calificaciones máximas.");
            return;
        }

        System.out.print("Ingrese la calificación de la película (1.0 a 10.0): ");
        if (scanner.hasNextFloat()) {
            float nota = scanner.nextFloat();
            scanner.nextLine();
            
            // Llama a tu método ingresarCalificacion()
            if (usuarioActivo.ingresarCalificacion(nota)) {
                System.out.println("Calificación guardada correctamente.");
            } else {
                System.out.println("Error: La calificación debe estar entre 1.0 y 10.0.");
            }
        } else {
            System.out.println("Error: Debe ingresar un valor numérico.");
            scanner.nextLine();
        }
    }

    private static void consultarCalificaciones() {
        // Llama a tu getter getContador()
        int total = usuarioActivo.getContador();
        if (total == 0) {
            System.out.println("No hay calificaciones registradas aún.");
            return;
        }
        
        System.out.println("\n--- Calificaciones Registradas ---");
        for (int i = 1; i <= total; i++) {
            // Llama a tu método obtenerCalificacion()
            System.out.println("Película #" + i + ": " + usuarioActivo.obtenerCalificacion(i) + " pts");
        }
    }

    private static void consultarUnaPelicula() {
        System.out.print("Ingrese el número de película que desea consultar: ");
        if (scanner.hasNextInt()) {
            int num = scanner.nextInt();
            scanner.nextLine();
            
            // Llama a tu método obtenerCalificacion()
            float resultado = usuarioActivo.obtenerCalificacion(num);
            if (resultado != -1.0f) {
                System.out.println("Película #" + num + ": " + resultado + " pts");
            } else {
                System.out.println("Error: El número ingresado no corresponde a una película registrada.");
            }
        } else {
            System.out.println("Error: Entrada no válida.");
            scanner.nextLine();
        }
    }

    private static void modificarCalificacion() {
        System.out.print("Ingrese el número de película a modificar: ");
        if (scanner.hasNextInt()) {
            int num = scanner.nextInt();
            System.out.print("Ingrese la nueva calificación (1.0 a 10.0): ");
            
            if (scanner.hasNextFloat()) {
                float nuevaNota = scanner.nextFloat();
                scanner.nextLine();
                
                // Llama a tu método modCal()
                if (usuarioActivo.modCal(num, nuevaNota)) {
                    System.out.println("Calificación modificada exitosamente.");
                } else {
                    System.out.println("Error: Posición no registrada o calificación fuera de rango (1-10).");
                }
            } else {
                System.out.println("Error: Formato de nota inválido.");
                scanner.nextLine();
            }
        } else {
            System.out.println("Error: Entrada inválida.");
            scanner.nextLine();
        }
    }

    private static void mostrarPromedio() {
        if (usuarioActivo.getContador() == 0) {
            System.out.println("No hay calificaciones registradas para calcular el promedio.");
        } else {
            // Llama a tu método promedio()
            System.out.printf("Promedio general: %.2f pts\n", usuarioActivo.promedio());
        }
    }

    private static void mostrarMejorYPeor() {
        if (usuarioActivo.getContador() == 0) {
            System.out.println("No hay calificaciones registradas.");
        } else {
            // Llama a tus métodos bestCal() y worstCal()
            System.out.println("Mejor calificación: " + usuarioActivo.bestCal() + " pts");
            System.out.println("Peor calificación: " + usuarioActivo.worstCal() + " pts");
        }
    }

    private static void consultarEspacios() {
        int registradas = usuarioActivo.getContador();
        // Llama a tu método obtenerEspaciosDisponibles()
        int disponibles = usuarioActivo.obtenerEspaciosDisponibles();
        System.out.println("Películas calificadas: " + registradas);
        System.out.println("Espacios disponibles: " + disponibles + " de 10");
    }
}