//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 8/12/2026
//  @ Author : 
//
//




public class Usuario {
    private String nombre;
    private String usuario;
    private int edad; // Corregido: 'int' en minúscula
    private float[] calificaciones;
    private int contadorCal; // Corregido: 'int' en minúscula

    // Constructor sin 'void' y con 'int'
    public Usuario(String nombre, String usuario, int edad) {
        this.nombre = nombre;
        this.usuario = usuario;
        this.edad = edad;
        this.calificaciones = new float[10];
        this.contadorCal = 0;
    }
    
    public String getNombre() {
        return nombre;
    }
    
    public String getUsuario() {
        return usuario;
    }

    public int getContador() { // Corregido: int
        return contadorCal;
    }
    
    public boolean ingresarCalificacion(float cal) {
        if (cal < 1.0f || cal > 10.0f) { // Corregido: ||
            return false;
        }
        if (!disponibilidad()) {
            return false;
        }

        calificaciones[contadorCal] = cal;
        contadorCal++;
        return true;
    }
    
    public float obtenerCalificacion(int numPel) { // Corregido: int
        int indice = numPel - 1;

        if (indice >= 0 && indice < contadorCal) {
            return calificaciones[indice];
        }
        return -1.0f; // Retorno en caso de error
    }
    
    public boolean modCal(int numPel, float newCal) { // Corregidos parametros a numPel y newCal
        int indice = numPel - 1; // Corregido: numPel
    
        if (indice < 0 || indice >= contadorCal) { // Corregido: ||
            return false;
        }
        
        if (newCal < 1.0f || newCal > 10.0f) { // Corregido: newCal
            return false;
        }
        
        calificaciones[indice] = newCal; // Corregido: newCal
        return true;
    }
    
    public float promedio() {
        if (contadorCal == 0) return 0.0f;
        
        float suma = 0.0f;
        for (int i = 0; i < contadorCal; i++) {
            suma += calificaciones[i];
        }
        return suma / contadorCal;
    }
    
    public float bestCal() {
        if (contadorCal == 0) return 0.0f; // Corregido: contadorCal (antes decía contador)
    
        float mayor = calificaciones[0];
        for (int i = 1; i < contadorCal; i++) {
            if (calificaciones[i] > mayor) {
                mayor = calificaciones[i];
            }
        }
        return mayor;
    }
    
    public float worstCal() {
        if (contadorCal == 0) return 0.0f; // Corregido: contadorCal (antes decía contador)
        
        float menor = calificaciones[0];
        for (int i = 1; i < contadorCal; i++) {
            if (calificaciones[i] < menor) {
                menor = calificaciones[i];
            }
        }
        return menor;
    }
    
    public boolean disponibilidad() {
        return contadorCal < 10;
    }

    public int obtenerEspaciosDisponibles() {
        return 10 - contadorCal; // Corregido: contadorCal (antes decía contador)
    }
}
